[package]
name = "experiments-lowlevel"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
num-traits = "0.2.19"
num_cpus = "1.16.0"
rayon = "1.10.0"
dynasm = "3.0.1"
dynasmrt = "3.0.1"
